name: Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.commits[0].message, '[ci-skip]')"
    steps:

      - uses: actions/checkout@v3

      - name: Build Nuxt app
        run: |
          echo ${{ secrets.ENV }} > .env
          npm install
          npm run build

      - name: Add SSH key
        run: |
          mkdir ~/.ssh
          echo "${{ secrets.OPENSSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      - name: Deploy files with rsync
        run: |
          rsync -rz meza-servers.nginx.conf root@${{secrets.HOST}}:/etc/nginx/sites-enabled/meza-servers.conf
          rsync -rz docker-compose.yml Dockerfile root@${{secrets.HOST}}:/opt/meza-servers/
          rsync -rz --delete --exclude '.env' .output/ root@${{secrets.HOST}}:/opt/meza-servers/app

      - name: Restart docker compose & nginx
        run: |
          ssh root@${{ secrets.HOST }} << 'EOF'
          cd /opt/meza-servers/
          docker compose build
          docker compose down
          docker compose up -d
          systemctl restart nginx
          EOF

      - name: Remove SSH files
        run: |
          rm ~/.ssh/id_rsa